version: 2
project_name: be-my-eyes

before:
  hooks:
    # Run tests before building
    - go mod tidy
    - go mod download

builds:
  - id: be-my-eyes
    main: ./cmd/be-my-eyes
    binary: be-my-eyes
    
    # Build for multiple platforms
    goos:
      - linux
      - darwin
    
    goarch:
      - amd64
      - arm64
    
    # Build flags
    ldflags:
      - -s -w
      - -X github.com/fboucher/be-my-eyes/internal/version.Version={{.Version}}
    
    # Configure cross-compilation for ARM64 Linux only
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_ENABLED=1
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=0
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    
    files:
      - README.md
      - LICENSE
      - QUICKSTART.md
      - ARCHITECTURE.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

# Debian/RPM packages
nfpms:
  - id: packages
    package_name: be-my-eyes
    vendor: François Boucher
    homepage: https://github.com/fboucher/be-my-eyes
    maintainer: François Boucher <frank@reka.com>
    description: TUI for interacting with the Reka Vision AI API
    license: MIT
    
    formats:
      - deb
    
    bindir: /usr/bin
    
    # Only build packages for Linux platforms
    builds:
      - be-my-eyes
    
    # Debian-specific metadata
    deb:
      fields:
        Priority: optional
    
    # Dependencies
    # Note: sqlite is a build dependency (CGO), not a runtime dependency for the binary

# Homebrew tap
brews:
  - name: be-my-eyes
    repository:
      owner: fboucher
      name: homebrew-tap
    
    homepage: https://github.com/fboucher/be-my-eyes
    description: "TUI for Reka Vision AI API"
    
    license: "MIT"
    
    dependencies:
      - name: sqlite

    install: |
      bin.install "be-my-eyes"

    test: |
      system "#{bin}/be-my-eyes", "--version"

# Future: Add AUR and other package managers
# For now, this provides a foundation for packaging