version: 2
project_name: be-my-eyes

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: brew-build
    main: ./cmd/be-my-eyes
    binary: be-my-eyes

    goos:
      - darwin

    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X github.com/fboucher/be-my-eyes/internal/version.Version={{.Version}}

    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

    files:
      - README.md
      - LICENSE
      - DEVELOPER.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - name: be-my-eyes
    repository:
      owner: fboucher
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

    homepage: https://github.com/fboucher/be-my-eyes
    description: "A Terminal User Interface (TUI) for analyzing/ summarizing/ questioning / searching into videos using AI"

    license: "MIT"

    install: |
      bin.install "be-my-eyes"

    test: |
      system "#{bin}/be-my-eyes", "--version"
